# Background of PCA
Say we are given a set $D = \{ ({\bf x}_{1}, y_1), ({\bf x}_{2}, y_2), \cdots, ({\bf x}_{N}, y_N) \} $, where each $y_i \in \{0, 1\}$ is the label for ${\bf x}_i \in \mathbb{R}^d$, a $d$ dimensional feature vector. We would like to know if we can reduce the dimensionality of features from 4 to 3, so we can envision it. We also want to find out how much "information" was lost in this dimensionality reduction.

As the first step we remove the mean from the data. To estimate the mean we use sample mean (unbiased ML estimation of the mean):

$$
{\hat {\bf x}}_{ML} = \frac{1}{N} \sum_{i=1}^N {\bf x}_i
$$

we define the mean-normalized row vector ${\bf b}_i$ as follows

$$
{\bf b}_i = ({\bf x}_i - {\hat {\bf x}}_{ML} )^T~~~,~i=1,...,N
$$

Using these we define the matrix ${ B}$ as follows

$$
B = \begin{bmatrix}
   -& {\bf b}_1 &-\\
   -&  {\bf b}_2 &-\\
    & \vdots & \\
   -&  {\bf b}_N &-
    \end{bmatrix}
$$
Here, each row is a mean-normalized feature vector (transposed).

We address two very similar ways to reduce dimensionality: with eigenvectors and with singular-value decomposition (SVD).

##Using SVD
You can find in most Linear Algebra texts the proof of SVD, that states that you can factor any real or complex $N \times d$ matrix into three factor-matrices:

$$
B= U \Sigma V^T   ~~~~~~~~~(1)
$$

where $U$ and $V$ are unitary matrices and $\Sigma$ is a diagonal matrix of singular values. $U$ is a square $N \times N$ matrix, $\Sigma$ is a diagonal, rectangular $N \times d$ matrix, and $V$ is a square $d \times d$ matrix.

**DEF: Unitary matrix** = an invertible, complex square matrix, $U$, is said to be "unitary" if its conjugate-transpose (also called its Hermitian transpose) is its also its inverse, so  $U^H\cdot U=(U^*)^T \cdot U=U\cdot U^H=I$. In our case, all our data is real-valued, so we need not bother with the commplex conjugate.

As we showed in the class, the principal components of the  data can be calculated by projecting the data into the matrix from equation $(1),~~~ V$

$$
T = B \cdot V
$$

Since we only work with real data and $V$ is a unitary matrix, then $VV^T = V^TV = I$.  

We interpret $V$ as the set of unit vectors along the axis of the new coordinate system. By projecting the data into these axis, you are changing the coordinate system from the original coordinate to the new coordinate where the features are independent among each other.  

The standard deviation of the data along each $i_{th}$ axis in this new cooordinate system is captured by the $\sigma_i$, where $\sigma_i$ is the $i_{th}$ diagonal element of the matrix $\Sigma$.

To reduce dimensionality, you select only the vectors of $V$ associated with the largest singular values in $\Sigma$, and project the data onto that subset of vectors.

##Using eigen-values and eigen-vectors
While SVD works for any shape rectangular matrix, such as our $N \times d$ matrix, $B$, eigen-values only work for square matrices.

*Observation:* If $B$ happened to be a square matrix already, then its eigenvalues would be the square of its singular values, $\lambda = \sigma^2$. However, for a general rectangular matrix, we cannot generalize this relationship, since we have to create the covariance matrix, scaling by $1/(N-1)$.

To use PCA to reduce dimensionality from $d$ to $k$, we follow these steps:

1. First mean-normalize the data, as mentioned above, so we have the $N \times d$ matrix of mean-normalized feature vectors, $B$
2. Next, create a square, unbiased, ML estimate of the covariance matrix of feature vectors from $B$, so $C=\frac{1}{N-1} B^T \cdot B $
3. Next, obtain the eigen-vector and eigen-value decomposition of $C$, where:
$$
C\cdot \vec{v}_i=\lambda_i \vec{v}_i~~,~~~~~i=1,...,d
$$
4. Next, select the $k$ largest eigen-values from the $d$ eigen-values obtained in step 3, and create a matrix with their associated eigen-vectors:
$$
V=\begin{bmatrix}
   |         &    & |\\
   \vec{v}_1 & \cdots & \vec{v}_k\\
   |         &    & |
    \end{bmatrix}
$$ (We happened to show indexes for the first $k$ eigen-vectors here because many functions in Matlab and Python return the decomposition with the eigen-values already sorted from largest to smallest. Make sure you select the largest ones.)
5. If the program has not already scaled the eigen-vectors to be unit-length, then do so now:
$$
\vec{u}_i = \frac{1}{||\vec{v}_i ||} \vec{v}_i ~~~~~~~ i=1, ... , k
$$
We are now ready to project our features onto the reduced dimensional feature space.
6. The matrix with reduced dimension feature vectors, $Z$ is
$$
Z= \begin{bmatrix}
   --  & \vec{u}_1^T  & --\\
    & \vdots  &  \\
   -- &  \vec{u}_k^T  & --
    \end{bmatrix}_{k \times d} \cdot
    \begin{bmatrix}
   |  &   & |\\
   \vec{x}^{(1)} & \cdots  & \vec{x}^{(N)} \\
   | &    & |
    \end{bmatrix}_{d \times N} \\
    =     \begin{bmatrix}
   |  &   & |\\
   \vec{z}^{(1)} & \cdots  & \vec{z}^{(N)} \\
   | &    & |
    \end{bmatrix}_{k \times N}
$$
7. Once we've trained my algorithm for classification or prediction, then any new instance that we wish to classify, or use for prediction must go through mean-normalization (step 1), and then projection onto the reduced-dimensional feature space (step 6).

##Reduction of Variance
The variance of our training set is our metric for information. Before PCA, the total variance from the original ($d$-dimensional) data is estimated to be:
$$
total~variance~original=\sum\limits_{j=1}^d \hat{\sigma}^2_{ML,j}
$$

The fraction-contribution of each feature is:
$$
proportion~from~feature~m=\frac{\hat{\sigma}^2_{ML,m}}{\sum\limits_{j=1}^d \hat{\sigma}^2_{ML,j}}~~~,~~m=1,...,d
$$
When you reduce the features' dimensions, you may want to limit the inforation you lost, so for example, you may want:
$$
\frac{total~variance~best~k~new~features}{total~variance~original} \ge 0.9
$$
This may place a constraint on how small $k$ is permitted to be.
***
***

**NOTE:** You are free to use SVD decomposition or eigenvevtor & eigenvalues to solve these problems. The choice is yours.

#Problem 1 [4 points]
Use the data that is generated in the next few lines to

*   Find the matrix $V$
*   Find the vectors that describe the new coordinate system in reduced diension $3$, and graph the data, so we can visualize it.

#Problem 2 [1 point]
*   Calculate how much the training set's variance has diminished. Have you preserved $90 \%$ of the variance?

***
***

The following code is provided to create 4-dimensional feature vectors collected in an $N \times 4$ matrix called "B":





In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # Import 3D plotting module

# Enable interactive mode for Google Colab
%matplotlib notebook

# Install Plotly
!pip install plotly

# Import Plotly
import plotly.express as px

# Set a random seed for reproducibility
np.random.seed(42)

# Define the number of vectors you want to generate
num_vectors = 100

# Generate random values for the first dimension
dim1 = np.random.randn(num_vectors)

# Create the second dimension with dependency on the first dimension and random noise
dependency_factor_dim2 = 0.7
noise_dim2 = np.random.randn(num_vectors)
dim2 = dependency_factor_dim2 * dim1 + 2 + noise_dim2

# Create the third dimension with dependency on the second dimension and random noise
dependency_factor_dim3 = -1.1
noise_dim3 = np.random.randn(num_vectors)
dim3 = dependency_factor_dim3 * dim2 - 4 + noise_dim3

# Generate random values for the fourth dimension
dim4 = np.random.randn(num_vectors)

# Create a 4-dimensional vector by stacking the dimensions horizontally
B = np.column_stack((dim1, dim2, dim3, dim4))

# Create a 3D scatter plot of the first three dimensions using   (allows you to rotate the figure with your mouse)
fig = px.scatter_3d(x=dim1, y=dim2, z=dim3, color=dim4)
fig.update_layout(title='Interactive 3D Scatter Plot of Dimensions 1, 2, 3', scene=dict(xaxis_title='x_1', yaxis_title='x_2', zaxis_title='x_3'))

# Show the plot
fig.show()


**Problem 1**

Find the matrix $V$

In [ ]:
# Calculate the unbiased sample covariance matrix
# C = np.cov(B, rowvar=False, bias=False)
# Normalize B by subtracting the mean along each dimension
B_normalized = B - np.mean(B, axis=0)
C = 1/(len(B)-1) * np.dot(np.transpose(B_normalized), B_normalized)

# Obtain the eigenvalues and eigenvectors of C
eigenvalues, eigenvectors = np.linalg.eig(C)

# Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Select the k largest eigenvalues and their associated eigenvectors
k = 3
selected_eigenvalues = eigenvalues[:k]
selected_eigenvectors = eigenvectors[:, :k]

# Create a matrix with the selected eigenvectors
# Z = np.dot(B_normalized, selected_eigenvectors)
Z = np.dot(selected_eigenvectors.T, B_normalized.T)


# Print the results
print("Unbiased Sample Covariance Matrix:")
print(C)

print("\nSelected 3 Eigenvalues:")
print(selected_eigenvalues)

print("\nV matrix:")
print(selected_eigenvectors)

print("\nThe vectors that describe the new coordinate system in reduced diension 3:")
print(Z.shape)
print(Z)





Unbiased Sample Covariance Matrix:
[[ 0.82476989  0.45918473 -0.31718095 -0.13667736]
 [ 0.45918473  1.14820587 -1.16935983 -0.11052422]
 [-0.31718095 -1.16935983  2.35893188  0.1213283 ]
 [-0.13667736 -0.11052422  0.1213283   0.78163531]]

Selected 3 Eigenvalues:
[3.19594692 0.90874676 0.69716409]

V matrix:
[[ 0.21543116  0.69557149  0.48414346]
 [ 0.5217725   0.21156703  0.25244289]
 [-0.82179994  0.3710635   0.2108495 ]
 [-0.0773805  -0.57769505  0.81081452]]

The vectors that describe the new coordinate system in reduced diension 3:
(3, 100)
[[-1.48929652e+00 -1.02920796e+00 -4.94749075e-01 -5.31498041e-02
   7.75508861e-01  1.20939850e+00  4.23923165e+00  9.59512905e-01
  -5.12273483e-01 -2.44248479e+00 -3.59453243e+00 -1.46536570e+00
  -3.12573703e-01  7.47837030e-01 -2.05349294e+00 -7.21914878e-01
  -5.40368790e-01 -9.10481906e-01  1.05713266e+00 -5.43102672e-01
   1.15243850e+00  7.37451041e-02  1.73713740e+00 -2.40833298e+00
   7.97618773e-01  2.61251394e+00 -2.79557065e+00  

Find the vectors that describe the new coordinate system in reduced diension $3$, and graph the data, so we can visualize it.

In [ ]:
import plotly.express as px
# Create a 3D scatter plot
fig = px.scatter_3d(x=Z[0, :], y=Z[1, :], z=Z[2, :], color=dim4)
# fig = px.scatter_3d(x=Z[:, 0], y=Z[:, 1], z=Z[:, 2], color=dim4)
fig.update_layout(
    title='Interactive 3D Scatter Plot in Reduced Dimension 3',
    scene=dict(
        xaxis_title='Reduced Dimension 1',
        yaxis_title='Reduced Dimension 2',
        zaxis_title='Reduced Dimension 3'
    )
)

# Show the plot
fig.show()

*Problem 2*

Calculate how much the training set's variance has diminished.

In [ ]:
# Calculate the total variance of the original data
total_variance_original = np.sum(np.var(B_normalized, axis=0))

# Calculate the total variance of the projected data
total_variance_projected = np.sum(np.var(Z, axis=1))
# total_variance_projected = np.sum(np.var(Z, axis=0))

# Calculate the percentage of variance preserved
variance_preserved_percent = (total_variance_projected / total_variance_original) * 100

# Print the results
print(f"Total Variance of Original Data: {total_variance_original}")
print(f"Total Variance of Projected Data: {total_variance_projected}")
print(f"Percentage of Variance Preserved: {variance_preserved_percent:.2f}%")

# Check if 90% of the variance is preserved
if variance_preserved_percent >= 90:
    print("Variance preservation meets or exceeds 90%.")
else:
    print("Variance preservation is below 90%. More principal components may be needed.")


Total Variance of Original Data: 5.062407538235173
Total Variance of Projected Data: 4.753839190050944
Percentage of Variance Preserved: 93.90%
Variance preservation meets or exceeds 90%.


In [ ]:
# Verify with PCA package.
import numpy as np
from sklearn.decomposition import PCA
import plotly.express as px

# Perform PCA using scikit-learn
pca_model = PCA(n_components=3)
B_pca_sklearn = pca_model.fit_transform(B)

# Access the eigenvalues and eigenvectors from the scikit-learn PCA model
covariance_matix_pca = pca_model.get_covariance()
eigenvalues_sklearn = pca_model.explained_variance_
eigenvectors_sklearn = pca_model.components_.T

# Print the eigenvalues and eigenvectors
print("Covariance:")
print(covariance_matix_pca)
print("\nEigenvalues:")
print(eigenvalues_sklearn)
print("\nEigenvectors:")
print(eigenvectors_sklearn)

# Visualize the data after PCA in a 3D scatter plot
fig_pca_sklearn = px.scatter_3d(x=B_pca_sklearn[:, 0], y=B_pca_sklearn[:, 1], z=B_pca_sklearn[:, 2])
fig_pca_sklearn.update_layout(title='3D Scatter Plot after PCA', scene=dict(xaxis_title='PC1', yaxis_title='PC2', zaxis_title='PC3'))
fig_pca_sklearn.show()


Covariance:
[[ 0.82476989  0.45918473 -0.31718095 -0.13667736]
 [ 0.45918473  1.14820587 -1.16935983 -0.11052422]
 [-0.31718095 -1.16935983  2.35893188  0.1213283 ]
 [-0.13667736 -0.11052422  0.1213283   0.78163531]]

Eigenvalues:
[3.19594692 0.90874676 0.69716409]

Eigenvectors:
[[ 0.21543116 -0.69557149  0.48414346]
 [ 0.5217725  -0.21156703  0.25244289]
 [-0.82179994 -0.3710635   0.2108495 ]
 [-0.0773805   0.57769505  0.81081452]]
